stages:
- runall-and-report-to-github-pending
- build
- set_exe_bit
- collate
- report-to-github-done

###############################################################################
# report result to github
###############################################################################
runall-and-report-to-github-pending:
  image: python:2.7
  stage: runall-and-report-to-github-pending
  script:
  - python reportCiResult.py "gitlab-ci" "pending"
  when: manual
  allow_failure: false

# Build
build_win:
  stage: build
  tags:
  - windows
  script:
  - external\unity\build-roslyn.bat
  artifacts:
    paths:
    - Artifacts/Builds
    expire_in: 1 week
# Important! Do not remove this after_script!!
  after_script:
    - C:\Users\builduser\post_build_script.bat

set_exe_bit_linux:
  stage: set_exe_bit
  tags:
  - linux
  dependencies:
  - build_win
  variables:
    GIT_STRATEGY: none
  script:
  - chmod -v +x Artifacts/Builds/Binaries/Linux/csc
  - ls -l Artifacts/Builds/Binaries/Linux/csc
  - chmod -v +x Artifacts/Builds/Binaries/Linux/VBCSCompiler
  - ls -l Artifacts/Builds/Binaries/Linux/VBCSCompiler
  artifacts:
    paths:
    - Artifacts/Builds/Binaries/Linux
    expire_in: 1 week
    
set_exe_bit_osx:
  stage: set_exe_bit
  tags:
  - darwin
  dependencies:
  - build_win
  variables:
    GIT_STRATEGY: none
  script:
  - chmod -v +x Artifacts/Builds/Binaries/Mac/csc
  - ls -l Artifacts/Builds/Binaries/Mac/csc
  - chmod -v +x Artifacts/Builds/Binaries/Mac/VBCSCompiler
  - ls -l Artifacts/Builds/Binaries/Mac/VBCSCompiler
  artifacts:
    paths:
    - Artifacts/Builds/Binaries/Mac
    expire_in: 1 week
    
collate_builds:
  image: ubuntu:latest
  stage: collate
  dependencies:
  - build_win
  - set_exe_bit_linux
  - set_exe_bit_osx
  variables:
    GIT_STRATEGY: none
  before_script:
  - apt-get update -qy && apt-get -qy upgrade
  - apt-get install -y p7zip-full p7zip-rar
  script:
  - cd Artifacts/Builds
  - 7z a ../../builds.7z *
  artifacts:
    paths:
    - builds.7z
    expire_in: 1 week
    
###############################################################################
# report result to github
###############################################################################
report-to-github-done:failure:
  image: python:2.7
  when: on_failure
  stage: report-to-github-done
  script:
  - python reportCiResult.py "gitlab-ci" "failure"

report-to-github-done:success:
  image: python:2.7
  when: on_success
  stage: report-to-github-done
  script:
  - python reportCiResult.py "gitlab-ci" "success"
