name: Build Roslyn

agent:
  type: Unity::VM
  image: xboxone/xboxone-build:latest
  flavor: b1.xlarge

commands:
  - git submodule update --init --recursive
  - external\unity\build-roslyn.bat

triggers:
  branches:
    only:
      - "/.*/"
  recurring:
    - branch: unity-master
      frequency: weekly

artifacts: 
  build:
    paths:
      - Artifacts/Builds/**