name: build

agent:
  type: Unity::VM
  image: xboxone/xboxone-build:latest
  flavor: b1.xlarge

commands:
  - git submodule update --init --recursive
  - external\unity\build-roslyn.bat

artifacts: 
  build:
    paths:
      - Artifacts/Builds/**