name: produce_artifacts

agent:
  type: Unity::VM
  image: cds-ops/ubuntu-18.04-agent:v1.0.11-765607
  flavor: b1.large

dependencies:
  - .yamato/build.yml
  - .yamato/set_exe_bit_linux.yml
  - .yamato/set_exe_bit_osx.yml

commands:
  - sudo DEBIAN_FRONTEND=noninteractive apt-get update -qy && sudo DEBIAN_FRONTEND=noninteractive apt-get -qy upgrade
  - sudo apt-get install -y p7zip-full p7zip-rar
  - mkdir producedbuilds
  - 7z a producedbuilds/builds.7z Artifacts/Builds/*
  - pwd
  - ls -al

triggers:
  branches:
    only:
      - "/.*/"
  recurring:
    - branch: unity-master
      frequency: weekly

artifacts: 
  builds:
    paths:
      - producedbuilds/builds.7z